Add config redirectEvenInFallbackMode
Leuchtfeuer/locate pull request #63
Opened 2024-12-09 13:32 UTC by Andreas-Sommer

allowing redirect to a site that will cause a language fallback

2024-12-27 10:18 UTC, davkraid requested changes

2024-12-27 10:18 UTC, davkraid commented on Classes/Verdict/Redirect.php
> +            $redirectEvenInFallbackMode = (bool) ($this->configuration['redirectEvenInFallbackMode'] ?? false);
Would name config option "allowFallback". Can you also mention it in the documentation under https://github.com/Leuchtfeuer/locate/blob/master/Documentation/Functions/AssignLanguage/Verdicts/Redirect.rst ?

2024-12-29 09:45 UTC, Andreas-Sommer commented on Classes/Verdict/Redirect.php
> +            $redirectEvenInFallbackMode = (bool) ($this->configuration['redirectEvenInFallbackMode'] ?? false);
Hey David,
change the parameter to allowFallback and updated the documentation.

2024-12-30 08:10 UTC, davkraid approved these changes

2025-01-06 08:59 UTC, bmheins approved these changes

2025-01-06 13:32 UTC, merged